server:
  port: 5000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: updat
  datasource:
    url: jdbc:mysql:localhost:3306/db_albums
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver


